name: Deploy to Server
description: 'Upload repository files to a server'
runs:
  using: 'composite'
  steps:
    -  uses: actions/checkout@v2
    -  run: |
        ssh-keyscan -p ${{github.events.input.port }} ${{ github.event.inputs.host }} > known_hosts
        echo "${{ github.event.inputs.secret_key }}" > sk
        chmod 400 sk
        ssh -o UserKnownHostsFile=known_hosts -i sk -p ${{github.events.input.port }} \
            ${{ github.event.inputs.username }}@${{ github.event.inputs.host }} 'rm -rf ${{github.events.input.path }}/*'
        scp -B -o UserKnownHostsFile=known_hosts -i sk -P ${{github.events.input.port }} -r public \
            ${{ github.event.inputs.username }}@$${{ github.event.inputs.host }}:${{github.events.input.path }}
        rm -f sk
      shell: bash
inputs:
  host:
    description: 'The host to upload files to'
    required: true
  username:
    description: 'sftp username'
    required: true
  path:
    description: 'absolute path on the destination server where files are uploaded'
    required: true
  port:
    description: 'ssh port'
    required: true
  secret_key:
    description: 'the secret key granting the username access to the server at server_url'
    required: true
