name: Deploy to Server
description: 'Upload repository files to a server'
runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: execute
      shell: bash
      run: |
        ssh-keyscan -p ${{ inputs.port }} ${{ inputs.host }} > known_hosts
        echo "${{ inputs.secret_key }}" > sk
        chmod 400 sk
        # Loop through non-hidden files in a dir one by one
        for file in *; do
            # delete the existing remote file by the same name
            ssh -o UserKnownHostsFile=known_hosts -i sk -p ${{ inputs.port }} ${{ inputs.user }}@${{ inputs.host }} 'rm -rf {{inputs.path}}/"$file"'
            # upload new version of file
            scp -B -o UserKnownHostsFile=known_hosts -i sk -P ${{ inputs.port }} -r "$file" ${{ inputs.user }}@${{ inputs.host }}:${{ inputs.path }}
        done
        rm -f sk
inputs:
  host:
    description: 'The host to upload files to'
    required: true
  user:
    description: 'sftp username'
    required: true
  path:
    description: 'absolute path on the destination server where files are uploaded'
    required: true
  port:
    description: 'ssh port'
    required: true
  secret_key:
    description: 'the secret key granting the username access to the server at server_url'
    required: true
